export const SOURCE_NAMES = [
  "All",
  "Commercial",
  "Government",
  "Independent Media",
  "News Media",
  "NGO",
  "Peer-Reviewed Publication",
  "Social Media Posts",
];

export const CHART_NAMES = [
  "All",
  "100% Stacked Barchart",
  "Areachart",
  "Bubble Map",
  "Bubblechart",
  "Choropleth Map",
  "Classic Barchart",
  "Flowchart",
  "Heatmap",
  "Instructional graphic",
  "Network",
  "Other Chart",
  "Other Map",
  "Piechart",
  "Radar",
  "Scatterplot",
  "Scientific Illustration",
  "Simple Stacked Barchart",
  "Spanchart",
  "Stacked Areachart",
  "Streamgraph",
  "Treemap",
];
